version: '3.6'
services:
  db:
    env_file:
      - ${ENV_FILE}
    image: courchevel:post_init
    ports:
      -
        published: ${POST_INIT_POSTGRES_HOST_PORT}
        target: 5432
    volumes:
      -
        type: volume
        source: db_1
        target: /var/lib/postgresql/data
volumes:
  db_1: