version: '3.6'
services:
  db:
    build:
      args:
        base_tag: 11.2-alpine
        init_scripts_path: ${DB_INIT_SCRIPTS_PATH}
      context: .
    env_file:
      - ${ENV_FILE}
    environment:
      - POSTGRES_USER=courchevel
      - POSTGRES_PASSWORD=courchevel
      - POSTGRES_DB=courchevel
    image: courchevel:latest
    ports:
      -
        published: ${POSTGRES_HOST_PORT}
        target: 5432
    volumes:
      -
        type: volume
        source: db_1
        target: /var/lib/postgresql/data
volumes:
  db_1: