name: appenv
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - jupyter=1.0
  - pandas=0.24
  - psycopg2=2.7
  - plotly=3.6
  - ptvsd=4.2.4
  - sqlalchemy=1.2
  - scikit-learn=0.20
