version: '3.6'
services:
  database:
    environment:
      - POSTGRES_USER=lesarcs
      - POSTGRES_PASSWORD=lesarcs
      - POSTGRES_DB=lesarcs
    image: postgres:11.2-alpine
    ports:
      -
        published: ${POSTGRES_HOST_PORT}
        target: 5432
  app:
    build:
      args:
        base_tag: 3.7.2-alpine3.8
      context: .
    command:
      - sh
    depends_on:
      - database
    env_file:
      - ${ENV_FILE}
    environment:
      TABLENAME: lutins
    tty: true
    volumes:
      - 
        type: bind
        source: ./app
        target: /app
