version: "3.6"
services:
  db:
    build:
      args:
        base_tag: "11.2-alpine"
        init_scripts_path: ${DB_INIT_SCRIPTS_PATH}
      context: ./db/
    container_name: ${PROJECT}_db_1
    env_file:
      - ${ENV_FILE}
    environment:
      - POSTGRES_USER=${PROJECT}
      - POSTGRES_PASSWORD=${PROJECT}
      - POSTGRES_DB=${PROJECT}
    image: ${PROJECT}_db:latest
    ports:
      -
        published: ${POSTGRES_DB_HOST_PORT}
        target: ${POSTGRES_DB_PORT}
    volumes:
      -
        type: volume
        source: db_1
        target: /var/lib/postgresql/data
  py:
    build:
      args:
        base_tag: "4.5.12"
        environment_file: ${PY_ENVIRONMENT_FILE}
        home: /usr/local/appuser
        user: appuser
      context: ./py/
    command: 
      - bash 
      - -ic 
      - 'jupyter lab --notebook-dir=/lab --no-browser --ip=0.0.0.0'
    container_name: ${PROJECT}_py_1
    depends_on:
      - db
    env_file:
      - ${ENV_FILE}
    environment:
      - JUPYTER_TOKEN=abc123
      - DB_HOST=${POSTGRES_DB_HOST}
      - DB_PORT=${POSTGRES_DB_PORT}
      - DB_NAME=${PROJECT}
      - DB_USER=${PROJECT}
      - DB_PASS=${PROJECT}
    image: ${PROJECT}_py:latest
    ports:
      -
        published: ${PY_DEBUG_PORT}
        target: 3000
      -
        published: ${PY_NOTEBOOK_PORT}
        target: 8888
    tty: true
    volumes:
      -
        type: bind
        source: ./py/lab
        target: /lab
      -
        type: bind
        source: ./py/app
        target: /app
  rs:
    build:
      args:
        base_tag: '3.5.2'
      context: ./rs/
    container_name: ${PROJECT}_rs_1
    depends_on:
      - db
    env_file:
      - ${ENV_FILE}
    environment:
      - PASSWORD=abc123
      - DB_HOST=${POSTGRES_DB_HOST}
      - DB_PORT=${POSTGRES_DB_PORT}
      - DB_NAME=${PROJECT}
      - DB_USER=${PROJECT}
      - DB_PASS=${PROJECT}
    image: ${PROJECT}_rs:latest
    ports:
      -
        published: ${RSTUDIO_PORT}
        target: 8787
    tty: true
    volumes:
      -
        type: bind
        source: ./rs/r
        target: /home/rstudio
volumes:
  db_1: