version: '3.6'
services:
  py:
    build:
      args:
        base_tag: 5.3.0
        conda_user: appuser
        conda_home: /appuser
      context: .
    command: bash -ic 'jupyter notebook --notebook-dir=/py_notebooks --no-browser --ip=0.0.0.0'
    environment:
      - JUPYTER_TOKEN=abc123
    image: saasfee:latest
    ports:
      -
        published: 18888
        target: 8888
    tty: true
    volumes:
      -
        type: bind
        source: ./py_notebooks
        target: /py_notebooks
